server:
  port: 31200
spring:
  application:
    name: kaixue-service-manage-course
  # 连接池选择策略以及配置方法 https://blog.csdn.net/varyall/article/details/87916767
  datasource:
    url: jdbc:mysql://localhost:3306/kx_course?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #type: com.alibaba.druid.pool.DruidDataSource #使用的连接池类型，默认是HikariCP
    driverClassName: com.mysql.cj.jdbc.Driver

    #可以通过添加druid-spring-boot-starter使druid配置生效，
    #也可以通过配置@configuration类使之生效 https://blog.csdn.net/u010513756/article/details/80235876
    druid:
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect #底层使用的数据库，因为mysql，Oracle这些是不同的
mybatis:
  mapper-locations: classpath:mapper/*.xml #mapper.xml文件路径
  configuration:
    map-underscore-to-camel-case: true #数据库字段对应实体类是驼峰式
pagehelper:
  helper-dialect: mysql #表明分页底层的数据库，因为mysql，Oracle这些是不同的

