server:
  port: 31000
spring:
  application:
    name: kaixue-service-cms-client
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017
      authentication-database: admin
      database: kx_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
kaixue:
  mq:
    #cms客户端监控的队列名称（不同客户端监听的队列不能重复）
    queue: queue_cms_postpage_01
    routing-key: 5fe82b91ee83fe1b98b43a82 #这个routingKey为门户站点id
