spring:
  application:
    name: kaixue-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017
      authentication-database: admin
      database: kx_cms
  freemarker:
    cache: false #关闭模板缓存
    settings:
      template_update_delay: 0  #更新检测延时为0
server:
  port: 31001
